<?php

namespace App\Filament\Resources\JadwalPenerbangan\Schemas;

use App\Models\Instruktur;
use App\Models\JadwalPenerbangan;
use App\Models\Pesawat;
use App\Models\Taruna;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TimePicker;
use Filament\Schemas\Schema;

class JadwalPenerbanganForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('kode_jadwal')
                    ->label('Schedule Code')
                    ->default(fn () => JadwalPenerbangan::generateKodeJadwal(now()->toDateString()))
                    ->readOnly()
                    ->required()
                    ->helperText('Automatically generated by system (Format: FLT-YYYYMMDD-XXX)')
                    ->prefixIcon('heroicon-m-qr-code'),

                DatePicker::make('tanggal')
                    ->label('Flight Date')
                    ->default(now()->toDateString())
                    ->live()
                    ->afterStateUpdated(function ($state, callable $set) {
                        if ($state) {
                            $set('kode_jadwal', JadwalPenerbangan::generateKodeJadwal($state));
                        }
                    })
                    ->required(),

                TimePicker::make('jam_mulai')
                    ->label('Start Time')
                    ->seconds(false)
                    ->required(),

                TimePicker::make('jam_selesai')
                    ->label('End Time')
                    ->seconds(false)
                    ->required(),

                Select::make('taruna_id')
                    ->label('Student / Cadet')
                    ->relationship('taruna', 'nama')
                    ->getOptionLabelFromRecordUsing(function (Taruna $record) {
                        $batch = ($record->batch ? "Batch {$record->batch}" : "") . ($record->status_batch ? "-{$record->status_batch}" : "");
                        $batchStr = $batch ? " | {$batch}" : "";
                        $modulStr = $record->modul_penerbangan ? " | Module: {$record->modul_penerbangan}" : "";
                        return "{$record->nama} (ID: {$record->nim}{$batchStr}{$modulStr})";
                    })
                    ->searchable()
                    ->preload()
                    ->live()
                    ->afterStateUpdated(function (callable $set) {
                        $set('modul_penerbangan', null);
                    })
                    ->required(),

                Select::make('instruktur_id')
                    ->label('Flight Instructor')
                    ->relationship('instruktur', 'nama')
                    ->getOptionLabelFromRecordUsing(fn (Instruktur $record) => "{$record->nama} ({$record->lisensi})")
                    ->searchable()
                    ->preload()
                    ->required(),

                Select::make('pesawat_id')
                    ->label('Training Aircraft')
                    ->relationship('pesawat', 'nomor_registrasi')
                    ->getOptionLabelFromRecordUsing(fn (Pesawat $record) => "{$record->nomor_registrasi} - {$record->tipe_pesawat} ({$record->nama_pesawat})")
                    ->searchable()
                    ->preload()
                    ->required(),

                Select::make('rute_area_latihan')
                    ->label('Training Route / Practice Area')
                    ->placeholder('-- Select Training Route / Area --')
                    ->options(function () {
                        return \App\Models\RuteAreaLatihan::where('is_active', true)
                            ->orderBy('kategori')
                            ->orderBy('nama_rute')
                            ->get()
                            ->groupBy('kategori')
                            ->map(fn ($group) => $group->pluck('nama_rute', 'nama_rute'))
                            ->toArray();
                    })
                    ->searchable()
                    ->preload()
                    ->required(),

                Select::make('modul_penerbangan')
                    ->label('Flight Training Module')
                    ->placeholder(fn ($get) => blank($get('taruna_id')) ? '-- Select Cadet First --' : '-- Select Cadet Flight Module --')
                    ->options(function ($get, ?JadwalPenerbangan $record) {
                        $tarunaId = $get('taruna_id');
                        if (blank($tarunaId)) {
                            return [];
                        }

                        $taruna = Taruna::with('modulPenerbangan')->find($tarunaId);
                        if (! $taruna) {
                            return [];
                        }

                        $options = [];

                        if ($taruna->modulPenerbangan->isNotEmpty()) {
                            $options = $taruna->modulPenerbangan
                                ->sortBy(['lisensi_target', 'kode_modul'])
                                ->mapWithKeys(fn ($item) => [
                                    $item->nama_modul => "{$item->nama_modul} (" . ($item->kode_modul ? "{$item->kode_modul} - " : "") . "{$item->standar_jam_terbang} Hrs)"
                                ])
                                ->toArray();
                        } elseif (!empty($taruna->modul_penerbangan)) {
                            $codes = array_map('trim', explode(',', $taruna->modul_penerbangan));
                            $options = \App\Models\ModulPenerbangan::where('is_active', true)
                                ->where(function ($q) use ($taruna, $codes) {
                                    $q->whereIn('kode_modul', $codes)
                                      ->orWhereIn('nama_modul', $codes)
                                      ->orWhere('lisensi_target', $taruna->modul_penerbangan);
                                })
                                ->orderBy('lisensi_target')
                                ->orderBy('kode_modul')
                                ->get()
                                ->mapWithKeys(fn ($item) => [
                                    $item->nama_modul => "{$item->nama_modul} (" . ($item->kode_modul ? "{$item->kode_modul} - " : "") . "{$item->standar_jam_terbang} Hrs)"
                                ])
                                ->toArray();
                        }

                        if ($record && $record->modul_penerbangan && !isset($options[$record->modul_penerbangan])) {
                            $options[$record->modul_penerbangan] = $record->modul_penerbangan;
                        }

                        return $options;
                    })
                    ->searchable()
                    ->preload()
                    ->disabled(fn ($get) => blank($get('taruna_id')))
                    ->dehydrated()
                    ->helperText(function ($get) {
                        $tarunaId = $get('taruna_id');
                        if (blank($tarunaId)) {
                            return 'Select a cadet first to display their assigned flight modules.';
                        }
                        $taruna = Taruna::with('modulPenerbangan')->find($tarunaId);
                        if ($taruna) {
                            $count = $taruna->modulPenerbangan->count();
                            if ($count > 0) {
                                return "Displaying {$count} modules assigned to {$taruna->nama}.";
                            }
                            return "Cadet {$taruna->nama} has no syllabus modules assigned yet.";
                        }
                        return null;
                    })
                    ->required(),

                Select::make('status')
                    ->label('Schedule Status')
                    ->options([
                        'draft' => 'Draft',
                        'scheduled' => 'Scheduled',
                        'in_flight' => 'In Flight',
                        'completed' => 'Completed',
                        'cancelled' => 'Cancelled',
                        'rescheduled' => 'Rescheduled',
                    ])
                    ->default('scheduled')
                    ->required(),

                Textarea::make('catatan')
                    ->label('Flight Notes / Briefing')
                    ->placeholder('Special route instructions, weather considerations, or briefing notes')
                    ->default(null)
                    ->columnSpanFull(),

                Hidden::make('created_by')
                    ->default(fn () => auth()->id()),

                DateTimePicker::make('published_at')
                    ->label('Publish Timestamp')
                    ->default(now()),
            ]);
    }
}
